openapi: 3.1.0

info:
  title: Resume API
  description: |
    The Resume API is your resume’s source of truth. Use it to store your resume and retrieve it for a variety of use cases. For example, you can use this service to display your resume on your website, or make it available as a PDF — all from a single source.
  contact:
    name: Christian Areas
    email: me@areas.me
  license:
    name: GNU General Public License v3.0
    identifier: GPL-3.0
  version: 0.1.0

servers:
  - url: 'http://localhost:3000/api'
    description: Local

tags:
  - name: Candidate
  - name: who
  - name: experience
  - name: skills
  - name: education

paths:
  '/candidate':
    # POST /candidate (createCandidate)
    post:
      tags:
        - Candidate
      operationId: createCandidate
      summary: Create a Candidate
      description: |
        Create a candidate in the system.
      requestBody:
        $ref: '#/components/requestBodies/createCandidate'
      responses:
        '201':
          $ref: '#/components/responses/candidateCreated'
        '400':
          $ref: '#/components/responses/candidateInfoMissingIncorrect'
        '409':
          $ref: '#/components/responses/candidateAlreadyExists'
  '/candidate/{candidateId}':
    # GET /candidate/{candidateId} (getCandidate)
    get:
      tags:
        - Candidate
      operationId: getCandidate
      summary: Get a Candidate
      description: |
        Get a candidate from the system.
      parameters:
        - $ref: '#/components/parameters/candidateId'
      responses:
        '200':
          $ref: '#/components/responses/candidate'
        '400':
          $ref: '#/components/responses/candidateInfoMissingIncorrect'
        '404':
          $ref: '#/components/responses/candidateNotFound'
    # PATCH /candidate/{candidateId} (updateCandidate)
    patch:
      tags:
        - Candidate
      operationId: updateCandidate
      summary: Update a Candidate
      description: |
        Update a candidate in the system.
      parameters:
        - $ref: '#/components/parameters/candidateId'
      requestBody:
        $ref: '#/components/requestBodies/updateCandidate'
      responses:
        '200':
          $ref: '#/components/responses/candidate'
        '400':
          $ref: '#/components/responses/candidateInfoMissingIncorrect'
        '404':
          $ref: '#/components/responses/candidateNotFound'
    # DELETE /candidate/{candidateId} (deleteCandidate)
    delete:
      tags:
        - Candidate
      operationId: deleteCandidate
      summary: Delete a Candidate
      description: |
        Delete a candidate from the system.
      parameters:
        - $ref: '#/components/parameters/candidateId'
      responses:
        '200':
          $ref: '#/components/responses/candidate'
        '400':
          $ref: '#/components/responses/candidateInfoMissingIncorrect'
        '404':
          $ref: '#/components/responses/candidateNotFound'

components:
  parameters:
    candidateId:
      name: candidateId
      in: path
      description: The candidate’s unique identifier.
      required: true
      schema:
        type: string
        format: uuid
        example: d5a5e5dc-f2dd-4f5a-8745-0e835d9f26a5

  requestBodies:
    # POST
    createCandidate:
      content:
        application/json:
          schema:
            $ref: './models/Candidate.yaml#/oneOf/1'
    # PATCH
    updateCandidate:
      content:
        application/json:
          schema:
            $ref: './models/Candidate.yaml#/oneOf/2'

  responses:
    # 200
    candidate:
      description: OK
      content:
        application/json:
          schema:
            $ref: './models/Candidate.yaml#/oneOf/0'
    # 201
    candidateCreated:
      description: Created
      content:
        application/json:
          schema:
            $ref: './models/Candidate.yaml#/oneOf/0'
    # 400
    candidateInfoMissingIncorrect:
      description: Candidate information missing or incorrect
    # 404
    candidateNotFound:
      description: Candidate not found
    # 409
    candidateAlreadyExists:
      description: Candidate already exists
