openapi: 3.1.0

info:
  title: Resume API
  summary: "The Resume API is your resume’s source of truth. Use it to store your resume and retrieve it for a variety of use cases. For example, you can use this service to display your resume on your website, or make it available as a PDF — all from a single source."
  description: |
    to-do
  contact:
    name: Christian Areas
    email: me@areas.me
  license:
    name: GNU General Public License v3.0
    identifier: GPL-3.0
  version: 0.1.0

servers:
  - url: http://localhost:3000/api
    description: Local

tags:
  - name: candidate
  - name: who
  - name: experience
  - name: skills
  - name: education

paths:
  /candidate:
    post:
      tags:
        - candidate
      operationId: createCandidate
      summary: Create a Candidate
      description: |
        Create a candidate in the system.
      requestBody:
        $ref: "#/components/requestBodies/createCandidate"
      responses:
        "201":
          $ref: "#/components/responses/candidateCreated"
        "400":
          description: Bad Request
        "409":
          description: Conflict

  "/candidate/{candidateId}":
    get:
      tags:
        - candidate
      operationId: getCandidate
      summary: to-do
      description: |
        to-do
      parameters:
        - name: candidateId
          in: path
          description: candidateId
          required: true
          schema:
            type: string
      responses:
        "200":
          $ref: "#/components/responses/candidate"
        "404":
          description: Not found
    patch:
      tags:
        - candidate
      operationId: updateCandidate
      summary: to-do
      description: |
        to-do
      parameters:
        - name: candidateId
          in: path
          description: candidateId
          required: true
          schema:
            type: string
      requestBody:
        description: |
          to-do
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Candidate"
        required: true
      responses:
        "200":
          $ref: "#/components/responses/candidate"
        "404":
          description: Not found
    delete:
      tags:
        - candidate
      operationId: deleteCandidate
      summary: to-do
      description: |
        to-do
      parameters:
        - name: candidateId
          in: path
          description: candidateId
          required: true
          schema:
            type: string
      responses:
        "200":
          $ref: "#/components/responses/candidate"
        "404":
          description: Not found

components:
  schemas:
    Candidate:
      $ref: "./models/Candidate.yaml"
    Who:
      $ref: "./models/Who.yaml"
    Experience:
      $ref: "./models/Experience.yaml"
    Skills:
      $ref: "./models/Skills.yaml"
    Education:
      $ref: "./models/Education.yaml"

  requestBodies:
    createCandidate:
      # description: |
      #   to-do
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Candidate/oneOf/1"

  responses:
    candidateCreated:
      description: Created
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Candidate/oneOf/0"
    candidate:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Candidate/oneOf/0"
