openapi: 3.1.0
info:
  title: Resume API
  summary: 'The Resume API is your resume’s source of truth. Use it to store your resume and retrieve it for a variety of use cases. For example, you can use this service to display your resume on your website, or make it available as a PDF — all from a single source.'
  description: |
    to-do
  contact:
    name: Christian Areas
    email: me@areas.me
  license:
    name: GNU General Public License v3.0
    identifier: GPL-3.0
  version: 0.1.0
servers:
  - url: 'http://localhost:3000/api'
    description: Local
tags:
  - name: candidate
  - name: who
  - name: experience
  - name: skills
  - name: education
paths:
  /candidate:
    post:
      tags:
        - candidate
      operationId: createCandidate
      summary: Create a Candidate
      description: |
        Create a candidate in the system.
      requestBody:
        description: 'An object that represents a candidate. It includes the candidate’s details, such as their name, email, phone number, and links to their social media profiles.'
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  description: The candidate’s first name.
                lastName:
                  type: string
                  description: The candidate’s last name.
                email:
                  type: string
                  format: email
                  description: The candidate’s email address.
                phoneCountryCode:
                  type: integer
                  description: The candidate’s phone country code.
                phoneNumber:
                  type: integer
                  description: The candidate’s phone number.
                website:
                  type: string
                  format: uri
                  description: The candidate’s website.
                linkedIn:
                  type: string
                  format: uri
                  description: The candidate’s LinkedIn.
                gitHub:
                  type: string
                  format: uri
                  description: The candidate’s GitHub.
              required:
                - firstName
                - lastName
                - email
            examples:
              createCandidateRequestExample:
                value:
                  firstName: Christian
                  lastName: Areas
                  email: me@areas.me
                  phoneCountryCode: 1
                  phoneNumber: 4088029811
                  linkedIn: 'https://www.linkedin.com/in/christianareas/'
                  gitHub: 'https://github.com/christianareas'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/Candidate.yaml
              examples:
                candidateResponseExample:
                  value:
                    candidateId: 5a5c5a84-5f20-4690-8b96-fb5f23cb1c5d
                    firstName: Christian
                    lastName: Areas
                    email: me@areas.me
                    phoneCountryCode: 1
                    phoneNumber: 4088029811
                    website: 'https://areas.me'
                    linkedIn: 'https://www.linkedin.com/in/christianareas/'
                    gitHub: 'https://github.com/christianareas'
  '/candidate/{candidateId}':
    get:
      tags:
        - candidate
      operationId: getCandidate
      summary: to-do
      description: |
        to-do
      parameters:
        - name: candidateId
          in: path
          description: candidateId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Candidate'
        '404':
          description: Not found
    patch:
      tags:
        - candidate
      operationId: updateCandidate
      summary: to-do
      description: |
        to-do
      parameters:
        - name: candidateId
          in: path
          description: candidateId
          required: true
          schema:
            type: string
      requestBody:
        description: |
          to-do
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Candidate'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Candidate'
        '404':
          description: Not found
    delete:
      tags:
        - candidate
      operationId: deleteCandidate
      summary: to-do
      description: |
        to-do
      parameters:
        - name: candidateId
          in: path
          description: candidateId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Candidate'
        '404':
          description: Not found
components:
  schemas:
    Candidate:
      $ref: ./models/Candidate.yaml
    Who:
      $ref: ./schemas/Who.yaml
    Experience:
      $ref: ./schemas/Experience.yaml
    Skills:
      $ref: ./schemas/Skills.yaml
    Education:
      $ref: ./schemas/Education.yaml
